### ISSUE TITLE
Bug in pathfinding algorithm.

### ISSUE THREAD

**Issue by Epicguru** [rafaeldolfe/Lost-in-the-Open#1]
Hey there!

Looks like you're using my threaded A* algorithm.
Recently while working on a new project, I found a bug in my old algorithm that you're using.

In your project, in `Pathfinding.cs`, change line 104 from:

`float priority = newCost + Heuristic(current, n);`
to
`float priority = newCost + Heuristic(n, end);`

Doing this will greatly increase performance. Currently the algorithm works but calculates the route very ineficiently, this will make it work as intended.
Apologies for my mistake.

**Comment by rafaeldolfe** [comment]
It was already working much faster than previously so I suppose that's pretty sweet. :) Thanks for letting me know James.

**Comment by rafaeldolfe** [comment]
How much of a performance boost is the change? @Epicguru

**Comment by Epicguru** [comment]
It's hard to quantify the performance increase.

I recommend checking out this website:
https://qiao.github.io/PathFinding.js/visual/

If you compare the A* against the Dijkstra on that page, then that is the difference it makes.

Good luck with your project, it's looking good so far!

**Comment by rafaeldolfe** [comment]
Gotcha. I seee 👍
